#!/usr/bin/python

# Copyright 2014 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""List of all tests.

    WARNING !!!

    by convention, all entries in the ALL_*_TEST_CLASSES dicts, including
    integration test entries, are executed in separate threads concurrently;
    be very careful with it; use it when you are confident that the tests do
    not interfere with each other at runtime; they do interfere in a couple of
    ways, for example: due to edits to a shared course content, due to changes
    to the shared configuration properties or course settings and so on;

    when needed, force groups of tests to execute serially; simply don't list
    them here individually, but do create a new empty test class that inherits
    the individual tests from all desired test classes via multiple inheritance;
    list each bundle class below individually and all tests within it will run
    serially, while all the entries themselves continue to run concurrently

    WARNING !!!

"""

__author__ = 'Pavel Simakov (psimakov@google.com)'


# here we list all integration tests that require an integration server
ALL_INTEGRATION_TEST_CLASSES = {
    'tests.integration.test_classes.IntegrationTestBundle1': 15,
    'tests.integration.test_classes.VisualizationsTest': 5,
    'tests.integration.test_classes.EmbedModuleTest': 4,
}

# here we list all functional and unit tests that run in-process
ALL_TEST_CLASSES = {
    'tests.functional.admin_settings.AdminSettingsTests': 1,
    'tests.functional.admin_settings.ExitUrlTest': 1,
    'tests.functional.admin_settings.HtmlHookTest': 17,
    'tests.functional.admin_settings.JinjaContextTest': 2,
    'tests.functional.admin_settings.WelcomePageTests': 2,
    'tests.functional.assets_rest.AssetsRestTest': 13,
    'tests.functional.common_crypto.EncryptionManagerTests': 5,
    'tests.functional.common_crypto.XsrfTokenManagerTests': 3,
    'tests.functional.common_crypto.PiiObfuscationHmac': 2,
    'tests.functional.common_crypto.GenCryptoKeyFromHmac': 2,
    'tests.functional.common_crypto.GetExternalUserIdTests': 4,
    'tests.functional.common_users.AppEnginePassthroughUsersServiceTest': 10,
    'tests.functional.common_users.AuthInterceptorAndRequestHooksTest': 2,
    'tests.functional.common_users.PublicExceptionsAndClassesIdentityTests': 2,
    'tests.functional.controllers_review.PeerReviewControllerTest': 7,
    'tests.functional.controllers_review.PeerReviewDashboardAdminTest': 1,
    'tests.functional.controllers_review.PeerReviewDashboardStudentTest': 2,
    'tests.functional.controllers_utils.LocalizedGlobalHandlersTest': 4,
    'tests.functional.i18n.I18NCourseSettingsTests': 7,
    'tests.functional.i18n.I18NMultipleChoiceQuestionTests': 6,
    'tests.functional.model_analytics.AnalyticsTabsWithNoJobs': 8,
    'tests.functional.model_analytics.CronCleanupTest': 14,
    'tests.functional.model_analytics.MapReduceSimpleTest': 1,
    'tests.functional.model_analytics.ProgressAnalyticsTest': 9,
    'tests.functional.model_analytics.QuestionAnalyticsTest': 3,
    'tests.functional.model_config.ValueLoadingTests': 2,
    'tests.functional.model_courses.CourseCachingTest': 5,
    'tests.functional.model_courses.PermissionsTest': 4,
    'tests.functional.model_data_sources.PaginatedTableTest': 17,
    'tests.functional.model_data_sources.PiiExportTest': 4,
    'tests.functional.model_entities.BaseEntityTestCase': 3,
    'tests.functional.model_entities.ExportEntityTestCase': 2,
    'tests.functional.model_entities.EntityTransformsTest': 4,
    'tests.functional.model_jobs.JobOperationsTest': 15,
    'tests.functional.model_models.BaseJsonDaoTestCase': 1,
    'tests.functional.model_models.ContentChunkTestCase': 16,
    'tests.functional.model_models.EventEntityTestCase': 1,
    'tests.functional.model_models.MemcacheManagerTestCase': 4,
    'tests.functional.model_models.PersonalProfileTestCase': 1,
    'tests.functional.model_models.QuestionDAOTestCase': 3,
    'tests.functional.model_models.StudentAnswersEntityTestCase': 1,
    'tests.functional.model_models.StudentLifecycleObserverTestCase': 13,
    'tests.functional.model_models.StudentProfileDAOTestCase': 6,
    'tests.functional.model_models.StudentPropertyEntityTestCase': 1,
    'tests.functional.model_models.StudentTestCase': 11,
    'tests.functional.model_permissions.PermissionsTests': 4,
    'tests.functional.model_permissions.SimpleSchemaPermissionTests': 16,
    'tests.functional.model_student_work.KeyPropertyTest': 4,
    'tests.functional.model_student_work.ReviewTest': 3,
    'tests.functional.model_student_work.SubmissionTest': 3,
    'tests.functional.model_utils.QueryMapperTest': 4,
    'tests.functional.model_vfs.VfsLargeFileSupportTest': 6,
    'tests.functional.module_config_test.ManipulateAppYamlFileTest': 8,
    'tests.functional.module_config_test.ModuleIncorporationTest': 12,
    'tests.functional.module_config_test.ModuleManifestTest': 7,
    'tests.functional.modules_data_pump.SchemaConversionTests': 1,
    'tests.functional.modules_data_pump.StudentSchemaValidationTests': 2,
    'tests.functional.modules_data_pump.PiiTests': 7,
    'tests.functional.modules_data_pump.BigQueryInteractionTests': 36,
    'tests.functional.modules_data_pump.UserInteractionTests': 4,
    'tests.functional.modules_data_removal.DataRemovalTests': 8,
    'tests.functional.modules_data_removal.UserInteractionTests': 16,
    'tests.functional.modules_data_source_providers.CourseElementsTest': 11,
    'tests.functional.modules_data_source_providers.StudentScoresTest': 6,
    'tests.functional.modules_data_source_providers.StudentsTest': 5,
    'tests.functional.modules_embed.DemoHandlerTest': 2,
    'tests.functional.modules_embed'
        '.ExampleEmbedAndHandlerV1ChildCoursesTest': 5,
    'tests.functional.modules_embed'
        '.ExampleEmbedAndHandlerV1SingleCourseTest': 3,
    'tests.functional.modules_embed.FinishAuthHandlerTest': 1,
    'tests.functional.modules_embed.GlobalErrorsDemoHandlerTest': 2,
    'tests.functional.modules_embed.JsHandlersTest': 3,
    'tests.functional.modules_embed.LocalErrorsDemoHandlerTest': 2,
    'tests.functional.modules_embed.RegistryTest': 3,
    'tests.functional.modules_embed.StaticResourcesTest': 1,
    'tests.functional.modules_embed.UrlParserTest': 12,
    'tests.functional.modules_extra_tabs.ExtraTabsTests': 7,
    'tests.functional.modules_gitkit'
        '.AccountChooserCustomizationHandlersTest': 2,
    'tests.functional.modules_gitkit.BaseHandlerTest': 3,
    'tests.functional.modules_gitkit.EmailMappingTest': 6,
    'tests.functional.modules_gitkit.EmailRestHandlerTest': 5,
    'tests.functional.modules_gitkit.RuntimeAndRuntimeConfigTest': 12,
    'tests.functional.modules_gitkit.GitkitServiceTest': 9,
    'tests.functional.modules_gitkit.OobChangeEmailResponseTest': 7,
    'tests.functional.modules_gitkit.OobFailureResponseTest': 6,
    'tests.functional.modules_gitkit.OobResetPasswordResponseTest': 7,
    'tests.functional.modules_gitkit.SignInContinueHandlerTest': 4,
    'tests.functional.modules_gitkit.SignInHandlerTest': 11,
    'tests.functional.modules_gitkit.SignOutContinueHandlerTest': 5,
    'tests.functional.modules_gitkit.SignOutHandlerTest': 2,
    'tests.functional.modules_gitkit.StudentFederatedEmailTest': 2,
    'tests.functional.modules_gitkit.WidgetHandlerTest': 2,
    'tests.functional.modules_gitkit.UsersServiceTest': 16,
    'tests.functional.modules_i18n_dashboard.CourseContentTranslationTests': 15,
    'tests.functional.modules_i18n_dashboard.IsTranslatableRestHandlerTests': 3,
    'tests.functional.modules_i18n_dashboard.I18nDashboardHandlerTests': 4,
    'tests.functional.modules_i18n_dashboard'
        '.I18nProgressDeferredUpdaterTests': 5,
    'tests.functional.modules_i18n_dashboard.LazyTranslatorTests': 5,
    'tests.functional.modules_i18n_dashboard.ResourceBundleKeyTests': 2,
    'tests.functional.modules_i18n_dashboard.ResourceRowTests': 6,
    'tests.functional.modules_i18n_dashboard'
        '.TranslationConsoleRestHandlerTests': 8,
    'tests.functional.modules_i18n_dashboard'
        '.TranslationConsoleValidationTests': 5,
    'tests.functional.modules_i18n_dashboard.TranslationImportExportTests': 53,
    'tests.functional.modules_i18n_dashboard.TranslatorRoleTests': 2,
    'tests.functional.modules_i18n_dashboard.SampleCourseLocalizationTest': 17,
    'tests.functional.modules_i18n_dashboard_jobs.BaseJobTest': 9,
    'tests.functional.modules_i18n_dashboard_jobs.DeleteTranslationsTest': 3,
    'tests.functional.modules_i18n_dashboard_jobs.DownloadTranslationsTest': 5,
    'tests.functional.modules_i18n_dashboard_jobs.RoundTripTest': 1,
    'tests.functional.modules_i18n_dashboard_jobs'
        '.TranslateToReversedCaseTest': 1,
    'tests.functional.modules_i18n_dashboard_jobs.UploadTranslationsTest': 5,
    'tests.functional.modules_invitation.InvitationHandlerTests': 16,
    'tests.functional.modules_invitation.ProfileViewInvitationTests': 5,
    'tests.functional.modules_invitation.SantitationTests': 1,
    'tests.functional.modules_manual_progress.ManualProgressTest': 24,
    'tests.functional.modules_notifications.CronTest': 9,
    'tests.functional.modules_notifications.DatetimeConversionTest': 1,
    'tests.functional.modules_notifications.ManagerTest': 31,
    'tests.functional.modules_notifications.NotificationTest': 8,
    'tests.functional.modules_notifications.PayloadTest': 6,
    'tests.functional.modules_notifications.SerializedPropertyTest': 2,
    'tests.functional.modules_notifications.StatsTest': 2,
    'tests.functional.modules_oeditor.ButtonbarCssHandlerTests': 2,
    'tests.functional.modules_oeditor.ObjectEditorTest': 4,
    'tests.functional.modules_oeditor.EditorPrefsTests': 6,
    'tests.functional.modules_questionnaire.QuestionnaireDataSourceTests': 2,
    'tests.functional.modules_questionnaire.QuestionnaireTagTests': 3,
    'tests.functional.modules_questionnaire.QuestionnaireRESTHandlerTests': 5,
    'tests.functional.modules_rating.ExtraContentProvideTests': 4,
    'tests.functional.modules_rating.RatingHandlerTests': 15,
    'tests.functional.modules_search.SearchTest': 12,
    'tests.functional.modules_skill_map.CompetencyMeasureTests': 4,
    'tests.functional.modules_skill_map.CountSkillCompletionsTests': 3,
    'tests.functional.modules_skill_map.GenerateCompetencyHistogramsTests': 1,
    'tests.functional.modules_skill_map.EventListenerTests': 4,
    'tests.functional.modules_skill_map.LocationListRestHandlerTests': 2,
    'tests.functional.modules_skill_map.SkillAggregateRestHandlerTests': 6,
    'tests.functional.modules_skill_map.SkillCompletionTrackerTests': 6,
    'tests.functional.modules_skill_map.SkillGraphTests': 11,
    'tests.functional.modules_skill_map.SkillI18nTests': 5,
    'tests.functional.modules_skill_map.SkillMapAnalyticsTabTests': 2,
    'tests.functional.modules_skill_map.SkillMapHandlerTests': 3,
    'tests.functional.modules_skill_map.SkillMapMetricTests': 10,
    'tests.functional.modules_skill_map.SkillMapRdfHandlerTests': 3,
    'tests.functional.modules_skill_map.SkillMapTests': 7,
    'tests.functional.modules_skill_map.SkillRestHandlerTests': 18,
    'tests.functional.modules_skill_map.StudentSkillViewWidgetTests': 6,
    'tests.functional.modules_unsubscribe.GetUnsubscribeUrlTests': 1,
    'tests.functional.modules_unsubscribe.SubscribeAndUnsubscribeTests': 4,
    'tests.functional.modules_unsubscribe.UnsubscribeHandlerTests': 4,
    'tests.functional.progress_percent.ProgressPercent': 4,
    'tests.functional.review_module.ManagerTest': 55,
    'tests.functional.review_peer.ReviewStepTest': 3,
    'tests.functional.review_peer.ReviewSummaryTest': 5,
    'tests.functional.student_answers.StudentAnswersAnalyticsTest': 1,
    'tests.functional.student_labels.StudentLabelsTest': 32,
    'tests.functional.student_last_location.NonRootCourse': 9,
    'tests.functional.student_last_location.RootCourse': 3,
    'tests.functional.student_tracks.StudentTracksTest': 10,
    'tests.functional.review_stats.PeerReviewAnalyticsTest': 1,
    'tests.functional.roles.RolesTest': 24,
    'tests.functional.upload_module.TextFileUploadHandlerTestCase': 8,
    'tests.functional.upload_module.TextFileUploadTagTestCase': 2,
    'tests.functional.test_classes.ActivityTest': 2,
    'tests.functional.test_classes.AdminAspectTest': 10,
    'tests.functional.test_classes.AssessmentPolicyTests': 6,
    'tests.functional.test_classes.AssessmentTest': 2,
    'tests.functional.test_classes.CourseAuthorAspectTest': 4,
    'tests.functional.test_classes.CourseAuthorCourseCreationTest': 1,
    'tests.functional.test_classes.CourseAuthorCourseDeletionTest': 7,
    'tests.functional.test_classes.CourseUrlRewritingTest': 48,
    'tests.functional.test_classes.DatastoreBackedCustomCourseTest': 6,
    'tests.functional.test_classes.DatastoreBackedSampleCourseTest': 48,
    'tests.functional.test_classes.EtlMainTestCase': 46,
    'tests.functional.test_classes.EtlTranslationRoundTripTest': 1,
    'tests.functional.test_classes.ExtensionSwitcherTests': 2,
    'tests.functional.test_classes.InfrastructureTest': 21,
    'tests.functional.test_classes.I18NTest': 2,
    'tests.functional.test_classes.LegacyEMailAsKeyNameTest': 48,
    'tests.functional.test_classes.LessonComponentsTest': 3,
    'tests.functional.test_classes.MemcacheTest': 69,
    'tests.functional.test_classes.MultipleCoursesTest': 1,
    'tests.functional.test_classes.NamespaceTest': 2,
    'tests.functional.test_classes.StaticHandlerTest': 3,
    'tests.functional.test_classes.StudentAspectTest': 20,
    'tests.functional.test_classes.StudentKeyNameTest': 8,
    'tests.functional.test_classes.StudentUnifiedProfileTest': 20,
    'tests.functional.test_classes.TransformsEntitySchema': 1,
    'tests.functional.test_classes.TransformsJsonFileTestCase': 3,
    'tests.functional.test_classes.VirtualFileSystemTest': 48,
    'tests.functional.test_classes.ImportActivityTests': 7,
    'tests.functional.test_classes.ImportAssessmentTests': 3,
    'tests.functional.test_classes.ImportGiftQuestionsTests': 1,
    'tests.functional.test_classes.WSGIRoutingTest': 3,
    'tests.functional.unit_assessment.UnitPartialUpdateTests': 6,
    'tests.functional.unit_assessment.UnitPrePostAssessmentTest': 18,
    'tests.functional.unit_description.UnitDescriptionsTest': 1,
    'tests.functional.unit_header_footer.UnitHeaderFooterTest': 11,
    'tests.functional.unit_on_one_page.UnitOnOnePageTest': 4,
    'tests.functional.whitelist.WhitelistTest': 13,
    'tests.unit.etl_mapreduce.HistogramTests': 5,
    'tests.unit.etl_mapreduce.FlattenJsonTests': 4,
    'tests.unit.common_catch_and_log.CatchAndLogTests': 6,
    'tests.unit.common_locales.LocalesTests': 2,
    'tests.unit.common_locales.ParseAcceptLanguageTests': 6,
    'tests.unit.common_menus.MenuTests': 6,
    'tests.unit.common_resource.ResourceKeyTests': 3,
    'tests.unit.common_schema_fields.CloneItemsNamedTests': 10,
    'tests.unit.common_schema_fields.ComplexDisplayTypeTests': 1,
    'tests.unit.common_schema_fields.DisplayTypeTests': 6,
    'tests.unit.common_schema_fields.FieldArrayTests': 3,
    'tests.unit.common_schema_fields.FieldRegistryTests': 7,
    'tests.unit.common_schema_fields.RedactEntityTests': 11,
    'tests.unit.common_schema_fields.SchemaFieldTests': 4,
    'tests.unit.common_safe_dom.NodeListTests': 4,
    'tests.unit.common_safe_dom.TextTests': 2,
    'tests.unit.common_safe_dom.ElementTests': 17,
    'tests.unit.common_safe_dom.ScriptElementTests': 3,
    'tests.unit.common_safe_dom.EntityTests': 11,
    'tests.unit.common_tags.CustomTagTests': 13,
    'tests.unit.common_utils.CommonUnitTests': 11,
    'tests.unit.common_utils.ParseTimedeltaTests': 8,
    'tests.unit.common_utils.ValidateTimedeltaTests': 6,
    'tests.unit.common_utils.ZipAwareOpenTests': 2,
    'tests.unit.javascript_tests.AllJavaScriptTests': 5,
    'tests.unit.models_analytics.AnalyticsTests': 6,
    'tests.unit.models_config.ValidateIntegerRangeTests': 3,
    'tests.unit.models_courses.WorkflowValidationTests': 13,
    'tests.unit.models_transforms.JsonToDictTests': 13,
    'tests.unit.models_transforms.JsonParsingTests': 3,
    'tests.unit.models_transforms.SchemaValidationTests': 21,
    'tests.unit.models_transforms.StringValueConversionTests': 2,
    'tests.unit.modules_search.ParserTests': 10,
    'tests.unit.test_classes.DeepDictionaryMergeTest': 5,
    'tests.unit.test_classes.EtlRetryTest': 3,
    'tests.unit.test_classes.InvokeExistingUnitTest': 5,
    'tests.unit.test_classes.ReviewModuleDomainTests': 1,
    'tests.unit.test_classes.SuiteTestCaseTest': 3,
    'tests.unit.gift_parser_tests.SampleQuestionsTest': 1,
    'tests.unit.gift_parser_tests.TestEssayAndNumericQuestion': 4,
    'tests.unit.gift_parser_tests.TestMatchQuestion': 3,
    'tests.unit.gift_parser_tests.TestMissingWordQuestion': 2,
    'tests.unit.gift_parser_tests.TestShortAnswerQuestion': 3,
    'tests.unit.gift_parser_tests.TestTrueFalseQuestion': 2,
    'tests.unit.gift_parser_tests.TestMultiChoiceMultipleSelectionQuestion': 3,
    'tests.unit.gift_parser_tests.TestHead': 2,
    'tests.unit.gift_parser_tests.TestMultiChoiceQuestion': 5,
    'tests.unit.gift_parser_tests.TestCreateManyGiftQuestion': 1,
}

INTERNAL_TEST_CLASSES = {}
